defaults:
  - _self_
  - augmentations: ressl.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "ressl-cifar10" # change here for cifar100
method: "ressl"
backbone:
  name: "resnet18"
method_kwargs:
  proj_output_dim: 256
  proj_hidden_dim: 4096
  base_tau_momentum: 0.99
  final_tau_momentum: 1.0
  momentum_classifier:
  temperature_q: 0.1
  temperature_k: 0.04
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.05
  classifier_lr: 0.1
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
