defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "supcon-cifar10" # change here for cifar100
method: "supcon"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  temperature: 0.2
data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "datasets/imagenet100/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.4
  classifier_lr: 0.1
  weight_decay: 1e-5
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
