defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "vibcreg-cifar10" # change here for cifar100
method: "vibcreg"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 200.0
  iternorm: True
data:
  dataset: cifar10 # change here for cifar100
  train_path: "./datasets"
  val_path: "datasets/imagenet100/val"
  format: "image_folder"
  num_workers: 4
augmentations:
  - rrc:
      enabled: True
      crop_min_scale: 0.2
      crop_max_scale: 1.0
    color_jitter:
      prob: 0.8
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.1
    grayscale:
      prob: 0.2
    gaussian_blur:
      prob: 0.0
    solarization:
      prob: 0.1
    equalization:
      prob: 0.0
    horizontal_flip:
      prob: 0.5
    crop_size: 32
    num_crops: 2
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
