defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mae-imagenet100-finetune"
pretrained_feature_extractor: None
backbone:
  name: "vit_base"
  kwargs:
    drop_path_rate: 0.1
pretrain_method: "mae"
data:
  dataset: imagenet100
  train_path: "./datasets/imagenet-100/train"
  val_path: "./datasets/imagenet-100/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "adamw"
  batch_size: 64
  lr: 5e-4
  weight_decay: 0.05
  layer_decay: 0.75
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.0
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
label_smoothing: 0.1
mixup: 0.8
cutmix: 1.0
finetune: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3, 4, 5, 6, 7]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
