defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "barlow_twins-imagenet"
method: "barlow_twins"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 4096
  lamb: 0.0051
  scale_loss: 0.048
data:
  dataset: imagenet
  train_path: "./datasets/imagenet/train"
  val_path: "./datasets/imagenet/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.8
  classifier_lr: 0.1
  weight_decay: 1.5e-6
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0, 1, 2, 3]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
