defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "pre-simclr-vit-B-csv-1.0"
method: "simclr"
backbone:
  name: "vit_base"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.2

# Dataset configuration
data:
  dataset: "custom"  # Using custom dataset type for CSV
  train_path: "/home/hammh0a/new/solo-learn/image_paths.csv"  # Path to CSV file containing image paths
  format: "csv"  # Specify CSV format
  num_workers: 8
  no_labels: True
  fraction: 1.0  # Use full dataset, adjust between 0.0-1.0 for partial dataset
  root_dir: "./"  # Root directory for relative image paths
  path_column: "path"  # Name of the column containing image paths in CSV

optimizer:
  name: "adamw"
  batch_size: 32
  lr: 0.002
  classifier_lr: 0.3
  weight_decay: 5e-2

scheduler:
  name: "warmup_cosine"
  scheduler_interval: "step"
  warmup_epochs: 1

checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  keep_prev: False

# Training parameters
max_epochs: 10
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto" #"ddp"
#precision: "bf16-mixed"
benchmark: True
accumulate_grad_batches: 2
seed: 0 
